[server]
headless = true
maxUploadSize = 100
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#5B4BDB"
backgroundColor = "#F7F9FD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#10233F"
font = "sans serif"
