[server]
headless = true
maxUploadSize = 100
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#4f46e5"
backgroundColor = "#f8fbff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
